// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FDFk7 {
	
	
	public partial class Bruger {
		
		protected System.Web.UI.HtmlControls.HtmlForm body;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl navbar;
		
		protected System.Web.UI.WebControls.TextBox txtBruger;
		
		protected System.Web.UI.WebControls.TextBox txtAdgang;
		
		protected System.Web.UI.WebControls.Button btnLogin;
		
		protected System.Web.UI.WebControls.Button btnDefault;
		
		protected System.Web.UI.WebControls.Button btnUdlejning;
		
		protected System.Web.UI.WebControls.Button btnOmOs;
		
		protected System.Web.UI.WebControls.Button btnKontakt;
		
		protected System.Web.UI.WebControls.Button btnBruger;
		
		protected System.Web.UI.WebControls.Button btnadminCreateMessage;
		
		protected System.Web.UI.WebControls.Button btnadminCreateUser;
		
		protected System.Web.UI.WebControls.Button btnadminCreateAdmin;
		
		protected System.Web.UI.WebControls.Button btnadminUseres;
		
		protected System.Web.UI.WebControls.Button btnadminHytte;
		
		protected System.Web.UI.WebControls.Button btnadminNyeReservation;
		
		protected System.Web.UI.WebControls.Button btnadminCMS;
		
		protected System.Web.UI.WebControls.Label lblTidspunkt;
		
		protected System.Web.UI.WebControls.Label lblBesked;
		
		protected System.Web.UI.WebControls.Label lblTekst;
		
		protected System.Web.UI.WebControls.Label lblLederTlf;
		
		protected System.Web.UI.HtmlControls.HtmlAnchor lnkLederMail;
		
		protected System.Web.UI.WebControls.Image lnkLederBillede;
		
		protected System.Web.UI.WebControls.Label lblLederTekst;
		
		protected System.Web.UI.WebControls.Image lnkArrBillede;
		
		protected System.Web.UI.WebControls.Label lblArrTitel;
		
		protected System.Web.UI.WebControls.Label lblArrTekst;
		
		protected System.Web.UI.WebControls.Label lblArrNote;
		
		protected System.Web.UI.WebControls.Label lblArrDato;
		
		protected System.Web.UI.WebControls.Label lblArrPris;
		
		protected System.Web.UI.WebControls.Label lblArrArrangoer;
	}
}
