// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FDFk7 {
	
	
	public partial class OmOs {
		
		protected System.Web.UI.HtmlControls.HtmlForm body;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl navbar;
		
		protected System.Web.UI.WebControls.TextBox txtBruger;
		
		protected System.Web.UI.WebControls.TextBox txtAdgang;
		
		protected System.Web.UI.WebControls.Button btnLogin;
		
		protected System.Web.UI.WebControls.Button btnDefault;
		
		protected System.Web.UI.WebControls.Button btnUdlejning;
		
		protected System.Web.UI.WebControls.Button btnOmOs;
		
		protected System.Web.UI.WebControls.Button btnKontakt;
		
		protected System.Web.UI.WebControls.Button btnBruger;
		
		protected System.Web.UI.WebControls.Button btnadminCreateMessage;
		
		protected System.Web.UI.WebControls.Button btnadminCreateUser;
		
		protected System.Web.UI.WebControls.Button btnadminCreateAdmin;
		
		protected System.Web.UI.WebControls.Button btnadminUseres;
		
		protected System.Web.UI.WebControls.Button btnadminHytte;
		
		protected System.Web.UI.WebControls.Button btnadminNyeResavationer;
		
		protected System.Web.UI.WebControls.Button btnadminCMS;
	}
}
