// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FDFk7 {
	
	
	public partial class Userdata {
		
		protected System.Web.UI.HtmlControls.HtmlForm body;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl navbar;
		
		protected System.Web.UI.WebControls.TextBox txtBruger;
		
		protected System.Web.UI.WebControls.TextBox txtAdgang;
		
		protected System.Web.UI.WebControls.Button btnLogin;
		
		protected System.Web.UI.WebControls.Button btnDefault;
		
		protected System.Web.UI.WebControls.Button btnUdlejning;
		
		protected System.Web.UI.WebControls.Button btnOmOs;
		
		protected System.Web.UI.WebControls.Button btnKontakt;
		
		protected System.Web.UI.WebControls.Button btnBruger;
		
		protected System.Web.UI.WebControls.Button btnadminCreateMessage;
		
		protected System.Web.UI.WebControls.Button btnadminCreateUser;
		
		protected System.Web.UI.WebControls.Button btnadminCreateAdmin;
		
		protected System.Web.UI.WebControls.Button btnadminUseres;
		
		protected System.Web.UI.WebControls.Button btnadminHytte;
		
		protected System.Web.UI.WebControls.Button btnadminNyeReservation;
		
		protected System.Web.UI.WebControls.Button btnadminCMS;
		
		protected System.Web.UI.WebControls.TextBox txtNavn;
		
		protected System.Web.UI.WebControls.TextBox txtAdr;
		
		protected System.Web.UI.WebControls.TextBox txtPostNr;
		
		protected System.Web.UI.WebControls.TextBox txtByNavn;
		
		protected System.Web.UI.WebControls.TextBox txtEmail;
		
		protected System.Web.UI.WebControls.TextBox txtTlf;
		
		protected System.Web.UI.WebControls.TextBox txtCPR;
		
		protected System.Web.UI.WebControls.TextBox txtSkole;
		
		protected System.Web.UI.WebControls.TextBox txtKlasse;
		
		protected System.Web.UI.WebControls.DropDownList ddlR1;
		
		protected System.Web.UI.WebControls.TextBox txtNavnR1;
		
		protected System.Web.UI.WebControls.TextBox txtEmailR1;
		
		protected System.Web.UI.WebControls.TextBox txtTlfR1;
		
		protected System.Web.UI.WebControls.DropDownList ddlR2;
		
		protected System.Web.UI.WebControls.TextBox txtNavnR2;
		
		protected System.Web.UI.WebControls.TextBox txtEmailR2;
		
		protected System.Web.UI.WebControls.TextBox txtTlfR2;
		
		protected System.Web.UI.WebControls.TextBox txtStivkrampe;
		
		protected System.Web.UI.WebControls.CheckBox chkPencilin;
		
		protected System.Web.UI.WebControls.CheckBox chkTilBilled;
		
		protected System.Web.UI.WebControls.TextBox txtAllergier;
		
		protected System.Web.UI.WebControls.TextBox txtNoter;
		
		protected System.Web.UI.WebControls.Button btnNySend;
		
		protected System.Web.UI.WebControls.Button btnUpdateSend;
	}
}
